import 'package:gohoubi_app/models/plan.dart';

class Accommodation {
  final int id;
  final String type, name, image, address, url;
  final List<Plan> plans;

  Accommodation({
    this.id,
    this.type,
    this.name,
    this.image,
    this.address,
    this.url,
    this.plans,
  });
}

List<Accommodation> _accommodations = [
  Accommodation(
    id: 0,
    type: '飲食店',
    name: '牛タン焼専門店司 西口名掛丁店',
    image: 'assets/images/tsukasa_shop.jpeg',
    address: '宮城県仙台青葉区',
    url: 'https://tabelog.com/miyagi/A0401/A040101/4018920/',
  ),
  Accommodation(
    id: 1,
    type: '飲食店',
    name: '御酒印船 仙台店',
    image: 'assets/images/goshuinsen_shop.jpeg',
    address: '宮城県仙台青葉区',
    url: 'https://tabelog.com/miyagi/A0401/A040101/4000613/',
  ),
  Accommodation(
    id: 2,
    type: '飲食店',
    name: '薫りと和酒 紬',
    image: 'assets/images/tsumugi_shop.jpg',
    address: '宮城県仙台青葉区',
    url: 'https://www.1noi.jp/%E7%B4%AC',
  ),
  Accommodation(
    id: 3,
    type: '飲食店',
    name: '御酒印船 仙台店',
    image: 'assets/images/goshuinsen_shop.jpeg',
    address: '宮城県仙台青葉区',
    url: 'https://tabelog.com/miyagi/A0401/A040101/4000613/',
  ),
  Accommodation(
    id: 4,
    type: '美容院',
    name: 'Agu hair jill 一番町店',
    image: 'assets/images/agu_shop.jpeg',
    address: '宮城県仙台市青葉区',
    url: 'https://beauty.hotpepper.jp/slnH000341560/',
  ),
  Accommodation(
    id: 5,
    type: 'マッサージ店',
    name: 'Raffine 仙台パルコ店',
    image: 'assets/images/raffine_shop.jpeg',
    address: '宮城県仙台市青葉区',
    url: 'https://beauty.hotpepper.jp/kr/slnH000142354/',
  ),
];

List<Accommodation> accommodations = [
  Accommodation(
    id: _accommodations[0].id,
    type: _accommodations[0].type,
    name: _accommodations[0].name,
    image: _accommodations[0].image,
    address: _accommodations[0].address,
    url: _accommodations[0].url,
    plans: [
      Plan(
        id: 0,
        price: 5000,
        title: 'oooo',
        description: 'hoge',
        image: 'assets/images/tsukasa_shop.jpeg',
        accommodation: _accommodations[0],
      ),
      Plan(
        id: 1,
        price: 5000,
        title: '0000',
        description: '紬の宴会コース。120分飲み放題（ラストオーダー100分）付きです。',
        image: 'assets/images/tsukasa_shop.jpeg',
        accommodation: _accommodations[0],
      ),
      Plan(
        id: 2,
        price: 5000,
        title: 'hoge',
        description: 'hoge',
        image: 'assets/images/tsukasa_shop.jpeg',
        accommodation: _accommodations[0],
      ),
      Plan(
        id: 3,
        price: 5000,
        title: 'hoge',
        description: 'hoge',
        image: 'assets/images/tsukasa_shop.jpeg',
        accommodation: _accommodations[0],
      ),
    ],
  ),
  Accommodation(
    id: _accommodations[1].id,
    type: _accommodations[1].type,
    name: _accommodations[1].name,
    image: _accommodations[1].image,
    address: _accommodations[1].address,
    url: _accommodations[1].url,
    plans: [
      Plan(
        id: 0,
        price: 5000,
        title: 'hoge',
        description: 'hoge',
        image: 'assets/images/goshuinsen_shop.jpeg',
        accommodation: _accommodations[1],
      ),
      Plan(
        id: 1,
        price: 5000,
        title: 'hoge',
        description: 'hoge',
        image: 'assets/images/goshuinsen_shop.jpeg',
        accommodation: _accommodations[1],
      ),
      Plan(
        id: 2,
        price: 5000,
        title: 'hoge',
        description: 'hoge',
        image: 'assets/images/goshuinsen_shop.jpeg',
        accommodation: _accommodations[1],
      ),
      Plan(
        id: 3,
        price: 5000,
        title: 'hoge',
        description: 'hoge',
        image: 'assets/images/goshuinsen_shop.jpeg',
        accommodation: _accommodations[1],
      ),
    ],
  ),
  Accommodation(
    id: _accommodations[2].id,
    type: _accommodations[2].type,
    name: _accommodations[2].name,
    image: _accommodations[2].image,
    address: _accommodations[2].address,
    url: _accommodations[2].url,
    plans: [
      Plan(
        id: 0,
        price: 5000,
        title: '宴会コース',
        description: '紬の宴会コース。120分飲み放題（ラストオーダー100分）付きです。',
        image: 'assets/images/tsumugi_ticket_1.jpg',
        accommodation: _accommodations[2],
      ),
      Plan(
        id: 1,
        price: 6500,
        title: '宴会コース',
        description: '紬の宴会コース。120分飲み放題（ラストオーダー100分）付きです。',
        image: 'assets/images/tsumugi_ticket_1.jpg',
        accommodation: _accommodations[2],
      ),
      Plan(
        id: 2,
        price: 8000,
        title: '雲宴会コース',
        description:
            '紬の宴会コース。120分飲み放題（ラストオーダー100分）付きです。ああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ',
        image: 'assets/images/tsumugi_ticket_1.jpg',
        accommodation: _accommodations[2],
      ),
    ],
  ),
  Accommodation(
    id: _accommodations[3].id,
    type: _accommodations[3].type,
    name: _accommodations[3].name,
    image: _accommodations[3].image,
    address: _accommodations[3].address,
    url: _accommodations[3].url,
    plans: [
      Plan(
        id: 0,
        price: 5000,
        title: 'hoge',
        description: 'hoge',
        image: 'assets/images/goshuinsen_shop.jpeg',
        accommodation: _accommodations[3],
      ),
      Plan(
        id: 1,
        price: 5000,
        title: 'hoge',
        description: 'hoge',
        image: 'assets/images/goshuinsen_shop.jpeg',
        accommodation: _accommodations[3],
      ),
      Plan(
        id: 2,
        price: 5000,
        title: 'hoge',
        description: 'hoge',
        image: 'assets/images/goshuinsen_shop.jpeg',
        accommodation: _accommodations[3],
      ),
      Plan(
        id: 3,
        price: 5000,
        title: 'hoge',
        description: 'hoge',
        image: 'assets/images/goshuinsen_shop.jpeg',
        accommodation: _accommodations[3],
      ),
    ],
  ),
  Accommodation(
    id: _accommodations[4].id,
    type: _accommodations[4].type,
    name: _accommodations[4].name,
    image: _accommodations[4].image,
    address: _accommodations[4].address,
    url: _accommodations[4].url,
    plans: [
      Plan(
        id: 0,
        price: 5000,
        title: 'hoge',
        description: 'hoge',
        image: 'assets/images/agu_shop.jpeg',
        accommodation: _accommodations[4],
      ),
      Plan(
        id: 1,
        price: 5000,
        title: 'hoge',
        description: 'hoge',
        image: 'assets/images/agu_shop.jpeg',
        accommodation: _accommodations[4],
      ),
      Plan(
        id: 2,
        price: 5000,
        title: 'hoge',
        description: 'hoge',
        image: 'assets/images/agu_shop.jpeg',
        accommodation: _accommodations[4],
      ),
      Plan(
        id: 3,
        price: 5000,
        title: 'hoge',
        description: 'hoge',
        image: 'assets/images/agu_shop.jpeg',
        accommodation: _accommodations[4],
      ),
    ],
  ),
  Accommodation(
    id: _accommodations[5].id,
    type: _accommodations[5].type,
    name: _accommodations[5].name,
    image: _accommodations[5].image,
    address: _accommodations[5].address,
    url: _accommodations[5].url,
    plans: [
      Plan(
        id: 0,
        price: 5000,
        title: 'hoge',
        description: 'hoge',
        image: 'assets/images/raffine_shop.jpeg',
        accommodation: _accommodations[5],
      ),
      Plan(
        id: 1,
        price: 5000,
        title: 'hoge',
        description: 'hoge',
        image: 'assets/images/raffine_shop.jpeg',
        accommodation: _accommodations[5],
      ),
      Plan(
        id: 2,
        price: 5000,
        title: 'hoge',
        description: 'hoge',
        image: 'assets/images/raffine_shop.jpeg',
        accommodation: _accommodations[5],
      ),
      Plan(
        id: 3,
        price: 5000,
        title: 'hoge',
        description: 'hoge',
        image: 'assets/images/raffine_shop.jpeg',
        accommodation: _accommodations[5],
      ),
    ],
  ),
];
